### ISSUE TITLE
Disable Reply ?

### ISSUE THREAD

**Issue by mokalo28** [otherwiseDE/DiscordTwitterBot#1]
Hello how to disable the Reply Twitter Thanks man have a nice Day

**Comment by otherwiseGG** [comment]
> Hello how to disable the Reply Twitter Thanks man have a nice Day

Hey mokalo!

This is something i didn't implement.
For this, you would need to filter the Twitter ID and only Filter the Tweets from only the Tweet Creator.

I dont know if i will implement this is in the future.

**Comment by otherwiseGG** [comment]
Replys have been disabled with the last Update.
